microsoft/AL

samples/HelloWorld/GreetingsManagement.al

Here is a danish greeting added

Added danish greeting

---

samples/HelloWorld/GreetingsManagement.al

See https://msdn.microsoft.com/en-us/library/dd355260.aspx

Random(int) is 1-based, afrikaan would never be selected.

---

samples/HelloWorld/GreetingsManagement.al

Not sure if I'm doing this right, so feel free to throw this one out :)

Added Pig Latin greeting

---

samples/HelloWorld/GreetingsManagement.al

4 new languages.
To be able to decently call the procedure, I moved the "1-based"-array fix to the Random-statement.  This way, you're able to call the procedure with a certain integer, and actually get back the value of that integer.. .

New languages and 1-based "random" solved a different way.

---

samples/HelloWorld/GreetingsManagement.al

Since I am from Lithuania, why not adding a greeting in my language. So here it is.

Added greeting from Lithuania

---

samples/HelloWorld/.vscode/launch.json
samples/HelloWorld/GreetingsManagement.al

In Single Tenancy, the single tenant is called default.
In Multi Tenancy, this shows how to specify a tenant (and works with a
default tenant out-of-the-box)

Support Multitenancy as well as Singletenancy

---

samples/HelloWorld/GreetingsManagement.al

I added some interesting greetings (such as Braille code, Morse code, 1337 language and etc.) to make it more fun.

Some changes for fun - Braille, Morse code and other interesting greetings

---

samples/HelloWorld/GreetingsManagement.al

Added Catalan

---

snippets/al.json

I tried to add the CaptionML snippet to quickly create ENU and example of usage for more languages.

CaptionML snippet

---

snippets/al.json

Action snippet added to create bare action with OnPush trigger.

Added Action snippet

---

snippets/al.json

Add two snippets to check for empty tables, either with or without an else branch. Inspired by http://vjeko.com/are-there-any-records-there/

Add snippets to check for empty tables

---

snippets/al.json

The teventsub snippet is missing a ] at the end.

Correction on teventsub snippet

---

README.MD

- Update readme to current version 0.11.14434
- Next Update is December update

Update Readme to current version

---

README.MD

@StanislawStempin I updated the ReadMe for the release. I have hide the Note. Do you want to treat bug reports separately release and preview?
- Update Text
- Update Version number
- Update Notice

Update ReadMe to Release

---

.gitignore

I have redesigned the gitignore so that other users can use it better.
>New design of the gitignore for Microsoft. Reason is a more professional
>appearance as well as more practical and general use.

Redesign gitignore

---

samples/HelloWorld/GreetingsManagement.al

Add Portuguese

---

snippets/table.json

Adding snippet for filed groups which automatically add the default two field groups DropDown and Brick.

feat(TableSnippet): Field groups snippet added

---

snippets/page.json
snippets/report.json

Whenever we required a new data item and column we have to type syntax every time which will take a long time to develop.

Snippet for dataitem and column in Report & for part in page

---

News.md

Adding a news file.
More to come.

Adding news file

---

.github/ISSUE_TEMPLATE/question.md
CONTRIBUTING.md
README.MD

The dynamicsuser.net forum no longer exists:

dynamicsuser.net removed

---

samples/HelloWorld/GreetingsManagement.al

added greeting in Telugu language

added greeting in Telugu language

---

snippets/query.json

Add a new Query snippet for the DataItemLink property.
Fixes [AB#539721](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539721)

Add DataItemLink property snippet.

---

.github/ISSUE_TEMPLATE/al-runtime-bug.md

An issue template to point requesters to use the official support process for runtime issues

New issue template for runtime issues

---

snippets/al.json

Would it make sense to update this snippet as this change was introduced some time ago?

remove '' from tevensub snippet
